### ISSUE TITLE
No brightness control?

### ISSUE THREAD

**Issue by Backu68** [baudneo/hass-addons#1]
I have (finally) gotten the CyncLAN bridge to work, and it turns on and off all my switches and BLE Bulbs.. but there doesn't appear to be any brightness control of said bulbs?

**Comment by baudneo** [comment]
Good lord, I am sorry for the super late reply. I hadnt seen this in my notifications or emails, at all. I just happened to be browsing the docs when I saw there was an open issue.

Are you still having this issue? I havent run into anything similar myself. I do have some older C by GE BTLE only bulbs that have all their functions working (rgb, on/off, brightness, white temp).

**Comment by Backu68** [comment]
So, brightness control works in Google Home, bit not in Home Assistant.. unless im missing something. And dont worry about the response time, I dont expect anyone to be working on side projects daily.

**Comment by baudneo** [comment]
Can you take a screenshot of one of the device pages? I'm interested in if the model # of the bulb is detected or if it says "unknown". 

To get to the device page, go to settings > devices and services > MQTT and search for "Savant". There should now be a filtered list of MQTT devices that are all Cync. Click on the problem bulb and the device page will open.


Are the brightness controls nowhere to be found? Or is there a brightness slider but it doesn't work?

<img width="682" height="802" alt="Image" src="https://github.com/user-attachments/assets/53115961-6066-43a2-a9be-2fbdab3a41dc" />

**Comment by baudneo** [comment]
If the device model is showing up as 'Unknown', it should still allow brightness because brightness is enabled by default for all lights in cync-lan. I would need to know if the brightness slider is exposed at all:

- Navigate to the MQTT device page for the bulb
  - `Settings > Devices & services > MQTT` (Click on the `X devices` text, not the MQTT integration card) and search for `Savant`
<img width="351" height="127" alt="Image" src="https://github.com/user-attachments/assets/b945ce45-7d25-4d72-a6ee-b24c2d7188c5" />

<img width="1820" height="412" alt="Image" src="https://github.com/user-attachments/assets/b040b25c-eda9-4c3b-ac3e-4fc3c76a6ccf" />
- Search and click on the bulb that has no brightness control, you are now on the MQTT device page

- Long press the light entity to get to the 'more info' modal

<img width="594" height="817" alt="Image" src="https://github.com/user-attachments/assets/8ae7ff75-1e9a-4175-8b94-4dde6afef0bf" />

- Take a screenshot or confirm if the brightness slider is there at all

It depends on if the brightness slider is exposed for the next troubleshooting steps.

**Comment by Backu68** [comment]
My apologies, turns out I'm an idiot and just didn't realize there was
brightness control.

**Comment by Backu68** [comment]
oddly enough, all my Cync devices are listed as unknown

**Comment by baudneo** [comment]
Usually, I see devices listed as "unavailable". Restarting cynclan should clear it up.

**Comment by Backu68** [comment]
Latest update broke this. It was working, I just wasn't finding it. Now, after updating today, I have no brightness control. And all devices are unknown still

<img width="317" height="336" alt="Image" src="https://github.com/user-attachments/assets/45e9d7b7-e83f-43d4-9fd5-3868e8da37ec" />

**Comment by Backu68** [comment]
<img width="608" height="580" alt="Image" src="https://github.com/user-attachments/assets/c233cd32-f1c9-4408-8c67-72fc7e21c8f2" />

**Comment by baudneo** [comment]
This is very strange. The only thing I updated was how the device sends it's config via mqtt.

What home assistant version are you on? Can you look at the Hass logs and search for 'cync' and see if there are any logging errors?

Also, I pushed new code, so it may already be fixed by a re-install (sorry for the hassle).

My immediate thought is you are running an older version of Hass, if that's not it, I'll take a look as soon as I'm home.

**Comment by Backu68** [comment]
I'm still relatively new to HA, but I'm not seeing any errors in the logs related to Cync.. also, now that I've done what I've done.. none of my Cync devices are connecting to HA and I'm just lost. They aren't connecting to Cync servers any longer, but they don't appear to be coming Available in HA, stay unavailable.

<img width="599" height="329" alt="Image" src="https://github.com/user-attachments/assets/b1a7a7f5-49b6-4a49-9152-69b9f88ffb50" />

**Comment by Backu68** [comment]
I've got too many devices on my network, and routed to the wrong IP.. they are talking to HA again, but still no brightness control

<img width="555" height="756" alt="Image" src="https://github.com/user-attachments/assets/8c6e61b9-1522-48ba-94a5-44559f89afe6" />
<img width="1658" height="59" alt="Image" src="https://github.com/user-attachments/assets/f9e308ff-0833-434e-964a-620b7603e7ff" />

**Comment by baudneo** [comment]
Alright, I need to see your config file. Do you know how to use SSH? and is the SSH addon installed on your HASS OS system?

If so and you SSH into it, please copy and paste the output of your config file, just the devices list ->

```bash
# starting right after ssh'ing into hass
cat /config/.storage/cync-lan/config/cync_mesh.yaml
```
The part I need to see is the device list, like so:

```yaml
    devices:
      1:
        fw: '4.8'
        is_plug: false
        mac: 78:6D:EB:28:EA:A3
        name: Makeup Lamp
        supports_rgb: true
        supports_temperature: true
        type: 31
        wifi_mac: 00:01:02:03:04:05
      2:
        fw: '4.8'
        is_plug: false
        mac: 78:6D:EB:28:EA:30
        name: Bsmt Hallway Light
        supports_rgb: true
        supports_temperature: true
        type: 31
        wifi_mac: 00:01:02:03:04:05
```

The other way to see your config file is to do another device export by visiting the cync-lan web UI and initiating an export, just like you did when first installing cync-lan. At the end of the export process, there is a text box with the full config file available to copy and paste.

**Comment by Backu68** [comment]
The "Current" .yaml for the bulb I've been referencing.. it's the same for all my bulbs though.. 

```
7:
        fw: '3.8'
        is_plug: false
        mac: A4:C1:38:58:04:5D
        name: Light 1
        supports_rgb: false
        supports_temperature: false
        type: 17
        wifi_mac: 00:01:02:03:04:05
```

**Comment by baudneo** [comment]
I see the problem. Device type 17 hasn't been seen yet, so cync-lan marks it as unknown and doesn't k ow it's capabilities (rgb, white temp, dynamic, etc.) however, it should, at a minimum allow you to dim it.

Can you tell me:
- the model #
- does it support rgb?
- Does it support white temp? (If not. What Kelvin is it set to) 
- is it a "dynamic" light?
- is it Bluetooth and wifi or just Bluetooth?

Once I k ow it's capabilities I can add support for that device type and all should be well.


Edit: also, IIRC, you can manually override the capabilities by settings `supports_rgb` and `supports_temperature` to true.

**Comment by Backu68** [comment]
I'll have to find the data for model and Kelvin, but it's a basic soft white dimmable bt bulb. No rgb, no wifi.

When I first started using Cync-lan, I had dimming properties, but when I updated it recently, dimming went away and its static on/off

**Comment by baudneo** [comment]
Have you reinstalled the add-on? If these bulbs are only dimmable. They should be dimmable in Hass as I set every cync light to support dimming by default as I haven't found a cync light that doesn't support dimming.

Your setup should "just work" if they are a bunch of non rgb and non white temp tunable bulbs. Even if they show as "unknown" on the device page.

**Comment by Backu68** [comment]
Yeah its installed again. The integration doesn't support bulbs, so I had do delete it and get thus back in, but for whatever reason, HASS is not showing them as disable, and google says they aren't setup brightness control

**Comment by baudneo** [comment]
I'm not sure what you mean by "the integration doesn't support bulbs". Even when a bulb is marked as "unknown", it has on/off and dimming capability, every single light that cync-lan controls has dimming capability by default (even if the light doesn't physically support it, but I haven't found a cync light that doesn't support brightness/dimming).

Something seems to be going on locally on your install, but I have no idea what it could be.

I think the best bet is for me to do a version bump when I'm home. After the version bump, when you go to the cync-lan add-on page (where the "start" "stop" "restart" "open web UI" buttons are), it should have a banner up top telling you that there is a new version available and to upgrade. When you upgrade, the image will be rebuilt and should pull any new changes in.

Edit: I am noticing in your screenshots of the mqtt messages, when cync-lan is sending an "on" command it is also sending brightness: 20. Every single "on" message in that screenshot is showing "brightness: 20".


Just to confirm so were both on the same page.
- you're installing cync-lan via HACS?
- have you done anything besides just installing it from HACS?

I'm going to copy your device config for the problem bulb and add it to my install to see if I can recreate your issue. Hopefully it gives me some insight into what's going on.

**Comment by Backu68** [comment]
Someone forked an integration, yours is an add on. And works better.

**Comment by baudneo** [comment]
> Someone forked an integration, yours is an add on. And works better.

Ah ok, now it's making sense. The whole reason I made this add-on is because that nikshriv cync integration that works via cloud didn't work for me very well.

As soon as I'm home from work I'll troubleshoot by replacing one of my bulbs config with the exact same as yours and see what's going on.

You're on Hass os 2025.12, so it's not the issue I thought it maybe could be. I have a hunch of what it is. Either way I'll roll out a version bump this evening to try and get it sorted. You'll see the upgrade option for cync-lan when I bump the version.

**Comment by baudneo** [comment]
Try this to get things working now:

Edit your config file and set each unknown bulb to device type: 31 instead of 17.

Make sure "supports_rgb" and "supports_temperature" are set to "false" or "no". Restart cync-lan and see if the light supports dimming. With this dirty hack, it may also tell you the bulb supports rgb and white temp in the UI by exposing a color wheel and a white temp slider, but they won't work.

What I think is happening is because it's an unknown device type number, it's not even recognizing it as a light and thinks it's a plug. Therefore it's only exposing on/off.

This is just a hunch, but overriding the device type should work until I push a fix out.

**Comment by baudneo** [comment]
I bumped the ver. I'm at work so couldn't test before pushing changes, but it should work for device type 17 now. 

I bumped to 0.0.3b2. in order to check for updates gonto settings -> add-ons and in the 3 dot menu. There is a "check for updates" option, click it. Navigate to the cync-lan add-on and it should now show that there is an upgrade to 0.0.3b2

It looks like Hass changed the front end UI lately. Here's a screenshot of the check for updates button on mobile:

![Screenshot_20251205_140247_Home Assistant.png](https://github.com/user-attachments/assets/18d1d262-c9c6-464c-917a-ff191b75821f)



https://github.com/baudneo/cync-lan/commit/b00d2e8acab285ee753da62642d9011f12c63520

**Comment by Backu68** [comment]
Updated, didn't change anything however. Also, HA core updated at the same time this started, so not sure if it could be related.

BTW, Model is CLED199L2, 2700k. BTW, Type 18 for this.. not sure why I have to different 'types'

**Comment by Backu68** [comment]
Alright, I tried going in and doing the true override on rgb and temp, nothing changed.

**Comment by Backu68** [comment]
So I did a workaround.. and it's rough I guess? Not sure where the types and capabilities are defined at as changing the lights to type 31 enables color and temp, even though both are set false in the yaml. But this allows for dimming.

**Comment by baudneo** [comment]
I need to know all device types. If you have an 18, it will have the same issue.

After you upgraded to 0.0.3b2, your type 17 lights don't work, but changing them to type 31 does work?

The bulb types are defined by Savant, not by me. The type is returned alongside other data when we query for the device list from the cloud API on export.

**Comment by Backu68** [comment]
So the bulbs, same bulbs, are listed as Type 17 and Type 18 for some odd reason. Setting as type 31 enables dimming, also gives the Color and Temp controls on HA, even though they don't work, and are set to false in the cync_lan.yaml. And yes, updated to 3b2.

**Comment by baudneo** [comment]
Ok, I just got home. Im on 0.0.3b1 and switched one of my bulbs to type 17. The bulb only has on/off, nothing else.

After upgrading to 0.0.3b2, same thing. I'm working on it and it will be fixed here shortly.

**Comment by baudneo** [comment]
Things should be working now, i bumped to b3 to get it out. Both 17 and 18 should now also be recognized on the device info page:

<img width="321" height="157" alt="Image" src="https://github.com/user-attachments/assets/c85f36de-8389-48e7-9499-7e7aaf1eadc7" />

**Comment by Backu68** [comment]
Updated.. still not quite right.. something is definitely off somewhere.. Bulbs will go dimmer, but not brighter.. and now switches are showing as dimmable

**Comment by baudneo** [comment]
Can you post every device type in the config file. Switch entities should not be showing a brightness slider unless they were configured as lights afaik.

**Comment by Backu68** [comment]
```
account data:
  Home:
    access_key:
    devices:
      1:
        fw: 1.5.636
        is_plug: false
        mac: 34:13:43:89:D4:CB
        name: Back Light
        supports_rgb: false
        supports_temperature: false
        type: 57
        wifi_mac: 34:13:43:89:FA:86
      2:
        fw: 1.5.636
        is_plug: false
        mac: 34:13:43:89:D5:01
        name: Kitchen Light
        supports_rgb: false
        supports_temperature: false
        type: 57
        wifi_mac: 34:13:43:89:FA:C3
      3:
        fw: 1.5.636
        is_plug: false
        mac: 34:13:43:89:D4:BB
        name: Dining Room Light
        supports_rgb: false
        supports_temperature: false
        type: 57
        wifi_mac: 34:13:43:89:FA:99
      4:
        fw: '3.8'
        is_plug: false
        mac: A4:C1:38:55:DF:A7
        name: Craftroom Overhead
        supports_rgb: false
        supports_temperature: false
        type: 18
        wifi_mac: 00:01:02:03:04:05
      5:
        fw: '3.8'
        is_plug: false
        mac: A4:C1:38:55:1B:0B
        name: Jacob's Overhead
        supports_rgb: false
        supports_temperature: false
        type: 17
        wifi_mac: 00:01:02:03:04:05
      6:
        fw: '3.8'
        is_plug: false
        mac: A4:C1:38:2C:BD:B8
        name: Light 2
        supports_rgb: false
        supports_temperature: false
        type: 17
        wifi_mac: 00:01:02:03:04:05
      7:
        fw: '3.8'
        is_plug: false
        mac: A4:C1:38:58:04:5D
        name: Light 1
        supports_rgb: false
        supports_temperature: false
        type: 17
        wifi_mac: 00:01:02:03:04:05
      8:
        fw: 1.0.052
        is_plug: false
        mac: 34:13:43:89:6C:BC
        name: Living Room Lamp
        supports_rgb: false
        supports_temperature: false
        type: 39
        wifi_mac: 34:13:43:89:73:2E
      9:
        fw: 1.0.052
        is_plug: false
        mac: 34:13:43:89:6F:E2
        name: Front Porch Light
        supports_rgb: false
        supports_temperature: false
        type: 39
        wifi_mac: 34:13:43:89:76:54
      10:
        fw: '3.8'
        is_plug: false
        mac: A4:C1:38:55:32:56
        name: Desk Light
        supports_rgb: false
        supports_temperature: false
        type: 18
        wifi_mac: 00:01:02:03:04:05

````

**Comment by baudneo** [comment]
For the brightness issue: I've fixed it upstream in the cync-lan repo. Try rebuilding the image using the 'rebuild image' button on the addon page and trying the brightness again. The scale was set to 0-255 instead of 0-100. If that doesnt work it will require:
- uninstall, re-install, set the configuration options up (cync username/password, mqtt broker info)
- OR I need to do a version bump to pull the fix in without an uninstall, re-install.

Can you get the model #'s for device type 39 and 57, as both of those devices have not been seen before?

I am assuming 57 is the switch, as known device types that are in the 50-59 range are switches. You can try setting the `is_plug` option to `true` or `yes` for the switch devices and restarting. It *may* set the HASS entity type to switch, which will remove the brightness slider and also change the light entity to an actual switch entity. Once I have the model # for the switch, I can add it to the known device types and it will function properly as an on/off switch.

The `is_plug`, `supports_rgb` and `supports_temperature` were all used in the old docker only cync-lan. When I did the re-write, I may have removed the manual overrides in favour of forcing users to submit device model #'s to expand known device types, I can't recall for sure.

Edit: It's nice to add 4 new device types. This will also give you a nice device info page like it did for device types 17 and 18.

Edit 2: If you cant get the switch model #, does the switch require a neutral? 
If you cant get the light model #, is it rgb? does it support white temp control, if not what kelvin is it set at? is it a dynamic light?

**Comment by Backu68** [comment]
57 is a no-neutral paddle-switch type, CSWONBLPWF1NN/ST1P, 39 is a standard paddle-switch type, CSWONBLPWF1/ST-1P. So far, no luck. nothing has changed.. but I'm doing a full uninstall (including deleting the /config/.storage/cync_lan/ and removing all MQTT devices... but having issues with OTP for the new install)

**Comment by Backu68** [comment]
I've gone totally pear shaped now.. can't control any lights at all, get an unknown error.. and Cync_LAN is all over my dashboard.

<img width="1561" height="747" alt="Image" src="https://github.com/user-attachments/assets/b206b3ac-031d-447b-a56d-46696938e60b" />

**Comment by Backu68** [comment]
Dashboard fixed itself, but lights don't operate now.. except 1

**Comment by baudneo** [comment]
I wouldnt delete the left over files or remove the MQTT devices. 

Are you manually sending/deleting/updating MQTT messages? Something is off here.

Device types 17 and 18 are working as expected on my end, and when you had the brightness scale issue, that proves the correct device config is being sent to the homeassistant light config topic at some point.

**Comment by Backu68** [comment]
That was the first time I manually did anything.. everything else was done through the UI as much as possible.. a full reinstall of HA and Cync-LAN has things working right though.

**Comment by baudneo** [comment]
Thats weird, but im glad things are working now.

Im just updating the 39 and 57 model #'s to show a nice formatted model description on the device info page. They should function as switches already in HASS, they just dont have a full nice model description like 17 and 18 have.

Edit: switch model info updated. If you rebuild the image, it may pull the new code in. Im going to do a version bump here shortly just to make sure everyone gets the new code.

**Comment by Backu68** [comment]
Oddly though, the switches are showing up with bolts for on/off instead of a slide switch.. any thoughts?

**Comment by baudneo** [comment]
> Oddly though, the switches are showing up with bolts for on/off instead of a slide switch.. any thoughts?
> 

That's how a switch entity works by default IIRC. It has an on/off instead of a slider. I think there is a way to get the slider back instead of the bolt and bolt with a line through it. I'll edit the post with details shortly.

**Comment by baudneo** [comment]
Just so I'm understanding properly. Is the switch displayed as two buttons everywhere? even after cync-lan has been running for awhile? Some sources online say it may just be the lovelace card (entities card maybe?) and using a different card may change that, but IDK. I uninstalled all my mains powered switches and strictly only run lights and wire free switches (wire free switches are NOT supported), so I cant test.

From what I understand, this is a HASS limitation and [they do not allow me to override this](https://community.home-assistant.io/t/mqtt-switch-shows-wrong-switch-icon/594629/5). You will need to add some lines to your configuration.yaml to turn the 2 buttons into a single toggle slider:

```
# This will work globally for ALL switches, no need to manually edit each entity
homeassistant:
  customize_domain:
    switch:
      assumed_state: false
```

From some reading online, it seems that there are 2 buttons by default if the switch doesnt know the state of the entity, basically its a blind switch and has no idea what the actual state of the device is. Which is wrong in this case, because the devices send out messages and cync-lan receives them, then publishes the device state to MQTT. So, at all times HASS knows the state of every cync device, even if a state change occurs outside HASS (like you turn a light off in the cync app or the light looses mains power, HASS will know about it).

It is unclear to me how I can force the toggle switch via a config, due to the HASS docs not having any information on this topic (that I can find or google-fu). So, you will need to edit your configuration.yaml to set the assumed_state attr for now, until I track down correct info on how/what/why HASS implemented things like this. 

It's aggravating because in their own docs, they say that setting the `optimistic` option to False and controlling state changes is the best way to do things, but then they do this and dont document it or make it easily searchable.

There are other options
-  you can use the customization to change the entity from a switch back to a light. It will work properly and have a single slider button like before.
- https://www.home-assistant.io/integrations/switch_as_x

These 2 options require manual work for EACH entity you want to change. To be clear, I dont like these workarounds at all, but I cant find the right info, if it exists, to get the desired result.

**Comment by baudneo** [comment]
I just tested the addon as it is now and it switched over to a single toggle after it received its first MQTT state message.

Here it is on first start, when only its availability has been set to `online` but it has no `status` topic:

<img width="679" height="245" alt="Image" src="https://github.com/user-attachments/assets/923065cb-9627-4cd8-8db4-e3946364f9f1" />

As soon as I sent the status topic a state message, it changed to a toggle switch:

<img width="715" height="247" alt="Image" src="https://github.com/user-attachments/assets/8c70ea05-59fa-408b-a3a2-30fef3222e73" />

If your switch entities are staying as the 2 button in the 'unknown' state, try manually toggling the physical button. If that works, it means I may need to see some raw debug logs from you as your devices may be sending a different payload on their first state messages OR these switches dont send their state on first connection to the server.

**Comment by Backu68** [comment]
Left overnight, haven't done any changes yet though, not sure if the configuration.yaml customize_domain fixes this. All switches have operated.

<img width="498" height="319" alt="Image" src="https://github.com/user-attachments/assets/7709a3fb-5579-4329-bcb6-7533ec1d4894" />

**Comment by baudneo** [comment]
Interesting, so maybe these switches have a completely different payload, or something similar is going on in the raw binary messages.

Can you:
- Enable debug logging by going to the addon configuration (where the cync account and mqtt broker details are) and enabling the debug logging switch and then clicking the 'save' button. The addon should ask to be restarted, if not, restart it manually.
- Go to the logging tab of the addon and look for messages about that specific device ID:

If in the config file the device is setup as:

```
1:
  name: blah
  mac: xx:yy:zz
```
Then its device ID is `1`

Look for messages about device ID 1. If we cant narrow it down there, I will have to add a raw binary debugging option to see what the devices are sending to the server.

Edit: actually wait, didnt these work before as lights? Still turn on debug logging and paste the output of the first few seconds after starting. It should have some details.

**Comment by Backu68** [comment]
Yes, originally they operated as 'lights' and had the slider, which just looks so much cleaner to me.

```
12/06/25 11:17:03.600 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Kitchen Light' (ID: 2)
12/06/25 11:17:03.600 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Light 1' (ID: 7)
12/06/25 11:17:03.600 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Living Room Lamp' (ID: 8)
12/06/25 11:17:03.600 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:17:03.601 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Back Light' (ID: 1)
12/06/25 11:17:03.601 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Craftroom Overhead' (ID: 4)
12/06/25 11:17:03.601 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Dining Room Light' (ID: 3)
12/06/25 11:17:03.601 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Light 2' (ID: 6)
12/06/25 11:17:03.601 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Desk Light' (ID: 10)
12/06/25 11:17:04.79 DEBUG [devices:1848] > 10.1.26.17: Requesting ALL device(s) status
12/06/25 11:17:04.332 DEBUG [devices:1637] > 10.1.26.17[9]:parse:x73: Setting TCP device Cync ID to: 9
12/06/25 11:17:04.332 DEBUG [devices:1681] > 10.1.26.17[9]:parse:0x73: Parsing initial connection device status data
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Living Room Lamp' (ID: 8)
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Kitchen Light' (ID: 2)
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Light 2' (ID: 6)
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Light 1' (ID: 7)
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Desk Light' (ID: 10)
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Back Light' (ID: 1)
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Craftroom Overhead' (ID: 4)
12/06/25 11:17:04.333 DEBUG [mqtt_client:522] > mqtt:device_status:'mesh info': Sending b'{"state": "OFF", "brightness": 0}' for device: 'Dining Room Light' (ID: 3)
12/06/25 11:17:08.223 DEBUG [devices:1251] > 10.1.26.19[8]:parse:0x43: Device sent TIMESTAMP -> 20240311:0012:-45,00042,00000,00007,00004 - replying...
12/06/25 11:17:11.810 DEBUG [devices:1251] > 10.1.26.17[9]:parse:0x43: Device sent TIMESTAMP -> 20240311:0012:-55,00054,00000,00009,00005 - replying...

```

**Comment by Backu68** [comment]
```
12/06/25 11:17:59.357 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Light 2" (ID: 6) = [6, 0, 0, 255, 0, 0, 0, 0]
12/06/25 11:17:59.357 WARNING [server:156] > nCync: Device ID: 6 ("Light 2") seems to have been removed from the BTLE mesh (lost power/connection), setting offline...
12/06/25 11:18:00.359 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Light 2" (ID: 6) = [6, 0, 0, 255, 0, 0, 0, 1]
12/06/25 11:18:00.359 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "OFF", "brightness": 0}' for device: 'Light 2' (ID: 6)
12/06/25 11:18:01.95 DEBUG [devices:1180] > 10.1.26.32[1]:parse:0xc3: CONNECTION REQUEST, replying...
12/06/25 11:18:39.369 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Light 1" (ID: 7) = [7, 0, 0, 255, 0, 0, 0, 0]
12/06/25 11:18:39.369 WARNING [server:156] > nCync: Device ID: 7 ("Light 1") seems to have been removed from the BTLE mesh (lost power/connection), setting offline...
12/06/25 11:18:39.369 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Desk Light" (ID: 10) = [10, 0, 0, 255, 0, 0, 0, 0]
12/06/25 11:18:39.369 WARNING [server:156] > nCync: Device ID: 10 ("Desk Light") seems to have been removed from the BTLE mesh (lost power/connection), setting offline...
12/06/25 11:18:40.373 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Light 1" (ID: 7) = [7, 0, 0, 255, 0, 0, 0, 1]
12/06/25 11:18:40.373 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "OFF", "brightness": 0}' for device: 'Light 1' (ID: 7)
12/06/25 11:18:41.388 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Desk Light" (ID: 10) = [10, 0, 0, 255, 0, 0, 0, 1]
12/06/25 11:18:41.388 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "OFF", "brightness": 0}' for device: 'Desk Light' (ID: 10)
12/06/25 11:18:53.378 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Kitchen Light" (ID: 2) = [2, 0, 0, 0, 0, 0, 0, 0]
12/06/25 11:18:53.378 WARNING [server:156] > nCync: Device ID: 2 ("Kitchen Light") seems to have been removed from the BTLE mesh (lost power/connection), setting offline...
12/06/25 11:18:53.378 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Dining Room Light" (ID: 3) = [3, 0, 0, 0, 0, 0, 0, 0]
12/06/25 11:18:53.378 WARNING [server:156] > nCync: Device ID: 3 ("Dining Room Light") seems to have been removed from the BTLE mesh (lost power/connection), setting offline...
12/06/25 11:18:54.374 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Kitchen Light" (ID: 2) = [2, 0, 0, 0, 0, 0, 0, 1]
12/06/25 11:18:54.374 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "OFF", "brightness": 0}' for device: 'Kitchen Light' (ID: 2)
12/06/25 11:18:54.375 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Dining Room Light" (ID: 3) = [3, 0, 0, 0, 0, 0, 0, 1]
12/06/25 11:18:54.375 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "OFF", "brightness": 0}' for device: 'Dining Room Light' (ID: 3)
12/06/25 11:19:06.386 DEBUG [devices:1406] > 10.1.26.19[8]:parse:0x83: Internal STATUS for "Front Porch Light" (ID: 9) = [9, 0, 0, 0, 0, 0, 0, 0]
12/06/25 11:19:06.386 WARNING [server:156] > nCync: Device ID: 9 ("Front Porch Light") seems to have been removed from the BTLE mesh (lost power/connection), setting offline...
12/06/25 11:19:08.355 DEBUG [devices:1406] > 10.1.26.19[8]:parse:0x83: Internal STATUS for "Front Porch Light" (ID: 9) = [9, 0, 0, 0, 0, 0, 0, 1]
12/06/25 11:19:08.355 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "OFF", "brightness": 0}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:19:31.386 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Desk Light" (ID: 10) = [10, 0, 0, 255, 0, 0, 0, 1]
12/06/25 11:19:31.386 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "OFF", "brightness": 0}' for device: 'Desk Light' (ID: 10)
12/06/25 11:19:39.389 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Light 1" (ID: 7) = [7, 0, 0, 255, 0, 0, 0, 0]
12/06/25 11:19:39.389 WARNING [server:156] > nCync: Device ID: 7 ("Light 1") seems to have been removed from the BTLE mesh (lost power/connection), setting offline...
12/06/25 11:19:47.387 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Light 1" (ID: 7) = [7, 0, 0, 255, 0, 0, 0, 1]
12/06/25 11:19:47.387 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "OFF", "brightness": 0}' for device: 'Light 1' (ID: 7)
12/06/25 11:19:59.969 DEBUG [mqtt_client:339] > mqtt:rcv: setting power to ON (non-JSON)
12/06/25 11:19:59.970 DEBUG [devices:325] > CyncDevice:Front Porch Light(9):set_power: Sent power state command, current: 0 - new: 1 to TCP devices: {'10.1.26.19': 1, '10.1.26.32': 1} in 0.00043 seconds
12/06/25 11:20:00.32 DEBUG [mqtt_client:522] > mqtt:device_status: Sending b'{"state": "ON"}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:20:00.169 DEBUG [mqtt_client:522] > mqtt:device_status: Sending b'{"state": "ON"}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:20:00.445 DEBUG [devices:1406] > 10.1.26.17[9]:parse:0x83: Internal STATUS for "Front Porch Light" (ID: 9) = [9, 1, 100, 0, 0, 0, 0, 1]
12/06/25 11:20:00.445 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "ON", "brightness": 0}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:20:02.116 DEBUG [mqtt_client:339] > mqtt:rcv: setting power to ON (non-JSON)
12/06/25 11:20:02.117 DEBUG [devices:325] > CyncDevice:Front Porch Light(9):set_power: Sent power state command, current: 1 - new: 1 to TCP devices: {'10.1.26.17': 1, '10.1.26.15': 1} in 0.00034 seconds
12/06/25 11:20:02.183 DEBUG [mqtt_client:522] > mqtt:device_status: Sending b'{"state": "ON"}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:20:02.432 DEBUG [mqtt_client:522] > mqtt:device_status: Sending b'{"state": "ON"}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:20:05.404 DEBUG [devices:1406] > 10.1.26.15[3]:parse:0x83: Internal STATUS for "Front Porch Light" (ID: 9) = [9, 1, 100, 0, 0, 0, 0, 1]
12/06/25 11:20:05.404 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "ON", "brightness": 100}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:20:05.680 DEBUG [devices:1406] > 10.1.26.32[1]:parse:0x83: Internal STATUS for "Front Porch Light" (ID: 9) = [9, 1, 100, 0, 0, 0, 0, 1]
12/06/25 11:20:05.681 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "ON", "brightness": 100}' for device: 'Front Porch Light' (ID: 9)
12/06/25 11:20:06.455 DEBUG [devices:1406] > 10.1.26.14[2]:parse:0x83: Internal STATUS for "Front Porch Light" (ID: 9) = [9, 1, 100, 0, 0, 0, 0, 1]
12/06/25 11:20:06.456 DEBUG [mqtt_client:522] > mqtt:device_status:0x83: Sending b'{"state": "ON", "brightness": 100}' for device: 'Front Porch Light' (ID: 9)
```

**Comment by baudneo** [comment]
I see the issue, pushing a fix now. Try rebuilding and hopefully it pulls the new code in, if it doesnt let me know and ill bump the version.  

I understand what you mean by cleaner, but HASS has a guide on best practices and how to expose devices to HASS, so users have a universal experience and things behave as HASS expects them. As showcased here, the switches have been incorrectly exposed as lights, which gave you a different experience than what is intended by the HASS devs. A weird edge case is dimmer switches which are setup as lights, so they have a brightness slider.

Thats why they have the built-in customizations and the 'switch as x' helper, so the end user can customize/show them however they like.

**Comment by Backu68** [comment]
![Image](https://github.com/user-attachments/assets/a82477dd-c085-4abf-ba08-3e31db96a782)

I did a rebuild, never did the ```configuration.yaml``` hack, however I did install the device as x. Keep up the great work man, sorry to have had so many issues this week

**Comment by baudneo** [comment]
Sorry I thought I bumped the version, I did it earlier today and it should pull in the new version when you upgrade. 

https://github.com/baudneo/cync-lan/commit/b147ce59f33c36084087cc254c973c2f3bef038e
